---
version: '2'
services:
  clickhouse-server:
    image: yandex/clickhouse-server:20.6
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    command: "bin/zkServer.sh start-foreground"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dominate:3:1,shadow:3:1"
    depends_on:
      - zookeeper
